/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as clerkWebhook from "../clerkWebhook.js";
import type * as createNewsArticle from "../createNewsArticle.js";
import type * as createUser from "../createUser.js";
import type * as getUser from "../getUser.js";
import type * as http from "../http.js";
import type * as images from "../images.js";
import type * as uploadFile from "../uploadFile.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  clerkWebhook: typeof clerkWebhook;
  createNewsArticle: typeof createNewsArticle;
  createUser: typeof createUser;
  getUser: typeof getUser;
  http: typeof http;
  images: typeof images;
  uploadFile: typeof uploadFile;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
